import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Nav from "@/components/Nav";
import Topbar from "@/components/Topbar";
import SplashScreen from "@/components/SplashScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="overflow-hidden bg-bgPrimary" lang="en">
      <body className={`flex flex-row ${inter.className}`}>
        <SplashScreen />
        <Nav />
        <div className="flex w-full flex-col">
          <Topbar />
          {children}
        </div>
      </body>
    </html>
  );
}
